// Generated by gencpp from file msglist/encoder.msg
// DO NOT EDIT!


#ifndef MSGLIST_MESSAGE_ENCODER_H
#define MSGLIST_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msglist
{
template <class ContainerAllocator>
struct encoder_
{
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
    : current_time()
    , encoder_left(0)
    , encoder_right(0)
    , count(0)  {
    }
  encoder_(const ContainerAllocator& _alloc)
    : current_time()
    , encoder_left(0)
    , encoder_right(0)
    , count(0)  {
  (void)_alloc;
    }



   typedef ros::Time _current_time_type;
  _current_time_type current_time;

   typedef int32_t _encoder_left_type;
  _encoder_left_type encoder_left;

   typedef int32_t _encoder_right_type;
  _encoder_right_type encoder_right;

   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::msglist::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msglist::encoder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_

typedef ::msglist::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::msglist::encoder > encoderPtr;
typedef boost::shared_ptr< ::msglist::encoder const> encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msglist::encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msglist::encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msglist

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msglist': ['/home/nvidia/catkin_ws_0104/src/msglist/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msglist::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msglist::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msglist::encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msglist::encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msglist::encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msglist::encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msglist::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b1c6272b050c70b84c5404bdc507e62";
  }

  static const char* value(const ::msglist::encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b1c6272b050c70bULL;
  static const uint64_t static_value2 = 0x84c5404bdc507e62ULL;
};

template<class ContainerAllocator>
struct DataType< ::msglist::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msglist/encoder";
  }

  static const char* value(const ::msglist::encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msglist::encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time current_time\n\
int32 encoder_left\n\
int32 encoder_right\n\
int32 count\n\
";
  }

  static const char* value(const ::msglist::encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msglist::encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_time);
      stream.next(m.encoder_left);
      stream.next(m.encoder_right);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msglist::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msglist::encoder_<ContainerAllocator>& v)
  {
    s << indent << "current_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.current_time);
    s << indent << "encoder_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_left);
    s << indent << "encoder_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_right);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGLIST_MESSAGE_ENCODER_H
